# Generated by Django 4.1.7 on 2023-04-10 11:20

import core.staging
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_column='UpdateAt')),
                ('member_image_url', models.ImageField(blank=True, null=True, upload_to=core.staging.upload_to)),
                ('member_name', models.CharField(max_length=80)),
                ('member_email', models.EmailField(db_index=True, max_length=254, verbose_name='email address')),
                ('member_phone', models.CharField(max_length=21)),
                ('occupation_Fr', models.CharField(max_length=80)),
                ('occupation_En', models.CharField(max_length=80)),
                ('experience_En', models.CharField(max_length=80)),
                ('experience_Fr', models.CharField(max_length=80)),
                ('bio_En', tinymce.models.HTMLField()),
                ('bio_Fr', tinymce.models.HTMLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
