# Generated by Django 3.2.18 on 2023-03-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='title_En',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='header',
            name='title_Fr',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio_En',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio_Fr',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='experience_En',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='member',
            name='experience_Fr',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='member',
            name='occupation_En',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='member',
            name='occupation_Fr',
            field=models.CharField(max_length=80),
        ),
    ]
