# Generated by Django 4.1.7 on 2023-04-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_column='UpdateAt')),
                ('name', models.CharField(max_length=80)),
                ('company', models.CharField(max_length=80)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email address')),
                ('subject', models.CharField(max_length=80)),
                ('message', models.TextField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
