# Generated by Django 4.1.7 on 2023-03-06 16:20

import core.staging
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_column='UpdateAt')),
                ('title_Fr', models.CharField(blank=True, max_length=80, null=True)),
                ('description_Fr', models.TextField(blank=True, null=True)),
                ('title_En', models.CharField(blank=True, max_length=80, null=True)),
                ('description_En', models.TextField(blank=True, null=True)),
                ('service_name_Fr', models.CharField(max_length=80)),
                ('service_name_En', models.CharField(max_length=80)),
                ('service_image_url', models.ImageField(upload_to=core.staging.upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
