# Generated by Django 3.2.18 on 2023-03-04 00:20

import core.staging
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_image_url',
            field=models.ImageField(upload_to=core.staging.upload_to),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name_En',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name_Fr',
            field=models.CharField(max_length=80),
        ),
    ]
