# Generated by Django 4.1.7 on 2023-03-06 16:28

import core.staging
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_column='UpdateAt')),
                ('title_Fr', models.CharField(blank=True, max_length=80, null=True)),
                ('description_Fr', models.TextField(blank=True, null=True)),
                ('title_En', models.CharField(blank=True, max_length=80, null=True)),
                ('description_En', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achivement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_column='UpdateAt')),
                ('project_completed', models.IntegerField(default=0)),
                ('satisfied_client', models.IntegerField(default=0)),
                ('team_members', models.IntegerField(default=0)),
                ('bands_joined', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_column='UpdateAt')),
                ('title_Fr', models.CharField(blank=True, max_length=80, null=True)),
                ('description_Fr', models.TextField(blank=True, null=True)),
                ('title_En', models.CharField(blank=True, max_length=80, null=True)),
                ('description_En', models.TextField(blank=True, null=True)),
                ('header_image_url', models.ImageField(upload_to=core.staging.upload_to)),
                ('video_link_url', models.URLField()),
                ('second_title_Fr', models.CharField(blank=True, max_length=80, null=True)),
                ('second_description_Fr', models.TextField(blank=True, null=True)),
                ('second_title_En', models.CharField(blank=True, max_length=80, null=True)),
                ('second_description_En', models.TextField(blank=True, null=True)),
                ('second_image', models.ImageField(upload_to=core.staging.upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryAndMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_column='UpdateAt')),
                ('history_Fr', models.CharField(blank=True, max_length=80, null=True)),
                ('history_description_Fr', models.TextField(blank=True, null=True)),
                ('history_En', models.CharField(blank=True, max_length=80, null=True)),
                ('history_description_En', models.TextField(blank=True, null=True)),
                ('mission_Fr', models.CharField(blank=True, max_length=80, null=True)),
                ('mission_description_Fr', models.TextField(blank=True, null=True)),
                ('mission_En', models.CharField(blank=True, max_length=80, null=True)),
                ('mission_description_En', models.TextField(blank=True, null=True)),
                ('vision_Fr', models.CharField(blank=True, max_length=80, null=True)),
                ('vision_description_Fr', models.TextField(blank=True, null=True)),
                ('vision_En', models.CharField(blank=True, max_length=80, null=True)),
                ('vision_description_En', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
