name: Créer une Pull Request

on:
  push:
    branches:
      - master

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "devmodou@gmail.com"

      - name: Créer une nouvelle branche
        run: git checkout -b dev

      - name: Faites vos modifications
        run: |
          # Effectuez vos modifications ici
          echo "Mes modifications one" >> fichier.txt

      - name: Commit et Push des modifications
        run: |
          git add .
          git commit -m "Ajouter mes modifications"
          git push origin dev

      - name: Créer une Pull Request
        run: |
          # Récupérer le nom de la branche actuelle
          CURRENT_BRANCH=$(git branch --show-current)
          
          # Créer la Pull Request en utilisant l'API GitHub
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
              "title": "Ma nouvelle Pull Request",
              "head": "dev",
              "base": "main",
              "body": "Description de la Pull Request"
            }' \
            "https://api.github.com/repos/b-hitech-corp/web_site_backend/pulls"
